apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-arc-upgrade-worker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{namespace}}:cr-upgrade-worker
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: {{namespace}}:crb-upgrade-worker
subjects:
 - kind: ServiceAccount
   name: sa-arc-upgrade-worker
   namespace: {{namespace}}
roleRef:
   kind: ClusterRole
   name: {{namespace}}:crb-upgrade-worker
   apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: arc-bootstrapper-upgrade-job
spec:
  template:
    spec:
      imagePullSecrets:
      - name: arc-private-registry
      containers:
      - name: bootstrapper
        image: mcr.microsoft.com/arcdata/arc-bootstrapper:v1.2.0_2021-12-15
        imagePullPolicy: Always
        command: ["/opt/bootstrapper/bin/bootstrapper"]
        args: ["-image", "mcr.microsoft.com/arcdata/arc-bootstrapper:v1.2.0_2021-12-15", "-policy", "Always", "-chart", "/opt/helm/arcdataservices", "-bootstrap"]
      restartPolicy: Never
      serviceAccountName: sa-arc-upgrade-worker
  backoffLimit: 0
---
apiVersion: arcdata.microsoft.com/v2
kind: DataController
metadata:
  name: arc
spec:
  docker:
    imageTag: v1.2.0_2021-12-15
