# See repository policies at ../../REPO_POLICIES.md
# ===========================================================================
# GitHub Repository Issue Management Policy
# ===========================================================================
# Purpose: Automate issue workflow management for the Arc Jumpstart repository
# This policy handles issue creation, triage, labeling, and lifecycle management
id: 
name: GitOps.PullRequestIssueManagement
description: Handlers for when an issue is first opened
owner: Arc Jumpstart
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    # ===========================================================================
    # EVENT RESPONDER TASKS
    # Defines automated actions triggered by specific GitHub events
    # These tasks create a streamlined workflow for issue management
    # ===========================================================================
    eventResponderTasks:
      # ---------------------------------------------------------------------------
      # NEW ISSUE MANAGEMENT
      # Handles initial triage and labeling of new issues
      # Automatically categorizes issues to improve visibility and tracking
      # ---------------------------------------------------------------------------
      - description: When an issue is opened, Identifiy if the issue title contains the word "bug" or "feature" and post a message to the author
        if:
          - payloadType: Issues
          - isAction:
              action: Opened
        then:
          # Start the triage process for all new issues
          - addLabel:
              label: Needs-Triage
          # Apply project-specific labels based on issue title keywords
          # This helps route issues to the right team members
          - if:
              # Identifiy if the issue title contains the word "arcbox" (not case insensitive)
              - titleContains:
                    pattern: "(?i)arcbox"
                    isRegex: true
            then:
                - addLabel:
                    label: ArcBox
          - if:
              # Identifiy if the issue title contains the word "hcibox" (not case insensitive)
              - titleContains:
                    pattern: "(?i)hcibox"
                    isRegex: true
            then:
                - addLabel:
                    label: HCIBox
          - if:
              # Identifiy if the issue title contains the word "agora" (not case insensitive)
              - titleContains:
                    pattern: "(?i)agora"
                    isRegex: true
            then:
                - addLabel:
                    label: Agora
          
          - if: 
              # Identifiy if the issue title contains the word "bug" (not case insensitive)
              # This auto-categorizes bug reports
              - titleContains:
                    pattern: "(?i)bug"
                    isRegex: true
            then:
                # Add Bug-Issue label to issues with the word "bug" in the title
                - addLabel:
                    label: Bug-Issue
                # Add a reply to the issue author with helpful guidance
                - addReply:
                    reply: |
                      👋 Hello ${issueAuthor},

                      Thank you for reporting this issue, a team member will review and triage it soon. All issues and pull requests are evaluated by the Arc Jumpstart team to determine next steps.

                      By submitting this issue request, you agree that your contributions will be licensed under the project's [MIT license](https://github.com/microsoft/azure_arc/blob/main/LICENSE-CODE) and you confirm that you've read and will abide by our [Code of Conduct](https://github.com/microsoft/azure_arc/blob/main/CODE_OF_CONDUCT.md).          
          - if:
              # Identifiy if the issue title contains the word "feature" (not case insensitive)
              # This auto-categorizes feature requests
              - titleContains:
                    pattern: "(?i)feature"
                    isRegex: true
            then:
                # Add Feature-Request label to issues with the word "feature" in the title
                - addLabel:
                    label: Feature-Request
                # Add a reply to the feature request author with expectations    
                - addReply:
                    reply: |
                      👋 Hello ${issueAuthor},

                      Thank you for your feature request, a team member will review it soon. All issues and pull requests are validated by the Arc Jumpstart team and must pass all validation checks before being merged.

                      By submitting this pull request, you agree that your contributions will be licensed under the [MIT license](https://github.com/microsoft/azure_arc/blob/main/LICENSE-CODE) license and you confirm that you've read and will abide by our [Code of Conduct](https://github.com/microsoft/azure_arc/blob/main/CODE_OF_CONDUCT.md).

      - description: Auto-close issues without Bug-Issue or Feature-Request labels
        # This policy ensures that any issue opened without the required labels is automatically closed.
        # It acts as a fail-safe mechanism to enforce the use of GitHub Issue Forms for proper categorization.
        if:
          - payloadType: Issues
          - isAction:
              action: Opened
          - and:
              # Check if the issue does not have the 'Bug-Issue' label
              - not:
                  hasLabel:
                      label: Bug-Issue
              # Check if the issue does not have the 'Feature-Request' label
              - not:
                  hasLabel:
                      label: Feature-Request
        then:
        - addReply:
            reply: |
                👋 Hello ${issueAuthor},

                This issue does not meet our repository's requirements for proper labeling. All issues must be submitted using our GitHub Issue Forms to ensure they are categorized correctly.

                This issue will now be closed. Please resubmit your issue or feature request [using the appropriate template](https://github.com/microsoft/azure_arc/issues/new/choose).

                Thank you for your collaboration!

        - closeIssue
        # Remove all working labels
        - removeLabel:
            label: Needs-Triage
        # Add abandoned label to track automatically closed non-form GitHub issues
        - addLabel:
            label: Abandoned

      # ---------------------------------------------------------------------------
      # ISSUE LIFECYCLE MANAGEMENT
      # Handles issue closing, reopening, and duplicate detection
      # Creates a consistent workflow for issue resolution
      # ---------------------------------------------------------------------------
      - description: Clear labels when an issue is closed
        # Auto-cleanup - removes working labels and adds resolution label
        # This keeps the label system clean and meaningful
        triggerOnOwnActions: false
        if:
        - payloadType: Issues
        - isAction:
            action: Closed
        then:
        # Remove all workflow labels as they're no longer needed
        - removeLabel:
            label: Needs-Triage
        - removeLabel:
            label: Needs-Attention
        - removeLabel: 
            label: Needs-Author-Feedback    
        # Mark as addressed for tracking metrics
        - addLabel:
            label: Issue-Addressed
        - addReply:
            reply: |
                👋 Hello ${issueAuthor},

                We've closed this issue because it has been addressed. If you believe further discussion is needed, please add a comment "`/unresolve`" to reopen the issue.

                Thank you for your collaboration!

      - description: Reopen unresolved issues
        # Triggered by the keyword "/unresolve" in comments
        # Allows authors to reopen issues for further discussion
        triggerOnOwnActions: false
        if:
        - payloadType: Issue_Comment
        - and:
            - commentContains:
                pattern: "(?i)unresolve"
                isRegex: True
        then:
        # Remove resolution labels to indicate unresolved status
        - removeLabel:
            label: Issue-Addressed
        - removeLabel:
            label: Resolution-Duplicate
        - removeLabel:
            label: No-Recent-Activity
        # Mark for author feedback
        - addLabel:
            label: Needs-Author-Feedback
        - addReply:
            reply: |
                👋 Hello ${issueAuthor},

                We've reopened this issue because you marked it as unresolved. We need more information from you or we identified it is not completely resolved. 

                Thank you for your collaboration!

        - reopenIssue

      - description: Add needs attention label to reopened issues
        # Ensures reopened issues get proper attention from maintainers
        triggerOnOwnActions: false
        if:
        - payloadType: Issues
        - isAction:
            action: Reopened
        then:
        # Clear resolution labels when an issue is reopened
        - removeLabel:
            label: Issue-Addressed
        - removeLabel:
            label: Resolution-Duplicate            
        # Mark for team attention
        - addLabel:
            label: Needs-Attention
        - addReply:
            reply: |
                👋 Hello ${issueAuthor},

                We've reopened this issue because we need more information from you or we identified it is not completely resolved.

                Thank you for your collaboration!

      # ---------------------------------------------------------------------------
      # ISSUE ASSIGNMENT HANDLING
      # Manages labels when issues are assigned or unassigned
      # ---------------------------------------------------------------------------
      - description: Remove Needs-Triage label when issue is assigned
        if:
          - payloadType: Issues
          - and:
              - isAction:
                  action: Assigned
              - hasLabel:
                  label: Needs-Triage
        then:
          - removeLabel:
              label: Needs-Triage

      - description: Add Needs-Triage label when issue has no assignees
        if:
          - payloadType: Issues
          - and:
             - not:
                isAssignedToSomeone
          - and:
             - not:
                hasLabel:
                    label: Needs-Triage
        then:
          - addLabel:
              label: Needs-Triage
          - removeLabel:
              label: Needs-Attention    

      - description: Handle when Needs-Triage is manually added to assigned issues
        if:
          - payloadType: Issues
          - and:
              - hasLabel:
                  label: Needs-Triage
              - isAssignedToSomeone
        then:
          - removeLabel:
              label: Needs-Triage
          - addLabel:
              label: Needs-Attention

      - description: Add back Needs-Attention label if removed from assigned issues
        if:
          - payloadType: Issues          
          - and:
             - not:
                hasLabel:
                    label: Needs-Attention
          - isAssignedToSomeone
        then:
          - addLabel:
              label: Needs-Attention

      # ---------------------------------------------------------------------------
      # DUPLICATE ISSUE HANDLING
      # Manages issues identified as duplicates in comments
      # Streamlines issue tracking by consolidating duplicates
      # ---------------------------------------------------------------------------
      - description: Add Resolution-Duplicate label to issues or PRs that are identified as duplicates
        # This rule detects comments containing variations of the word "duplicate" and marks the issue accordingly
        triggerOnOwnActions: false
        if:
        - payloadType: Issue_Comment
        - and:
            # Look for various forms of "duplicate" in comments
            - commentContains:
                pattern: "(?i)duplicat(e|ed|ing)?"
                isRegex: True
        then:
        - addReply:
            reply: |
                ⚠️ **WARNING: Duplicate Issue** ⚠️
                
                👋 Hello ${issueAuthor},

                We've identified this as a duplicate of another issue or PR that already exists. This specific instance is being closed in favor of the linked issue. Please add your 👍 to the other issue to raise its priority.

                Thank you for your collaboration!

        - closeIssue
        # Remove all working labels
        - removeLabel:
            label: Needs-Triage
        - removeLabel:
            label: Needs-Attention
        - removeLabel:
            label: Needs-Feedback-Hub
        - removeLabel:
            label: Needs-Author-Feedback
        # Add resolution label
        - addLabel:
            label: Resolution-Duplicate
 
    # ===========================================================================
    # SCHEDULED SEARCHES
    # Periodic tasks that run on defined schedules to maintain repository hygiene
    # ===========================================================================
    scheduledSearches:
    # ---------------------------------------------------------------------------
    # STALE ISSUE MANAGEMENT
    # Automatically closes issues that need feedback but have no activity
    # ---------------------------------------------------------------------------
    - description: Close stale issues. Issues that have not had any activity for 7 days and are labeled with Needs-Author-Feedback and No-Recent-Activity will be closed.
      # This runs daily at 6:00 and closes issues after the warning period has elapsed
      frequencies:
      - hourly:
          hour: 6
      filters:
      # Only target issues that are open and need author feedback
      # Exclude issues that are labeled with Feature-Request or Upstream-Bug-Issue    
      - isIssue
      - isOpen
      - hasLabel:
          label: Needs-Author-Feedback
      - hasLabel:
          label: No-Recent-Activity
      # Exclude issues that may need longer response times
      - isNotLabeledWith:
          label: Feature-Request
      - isNotLabeledWith:
          label: Upstream-Bug-Issue             
      - noActivitySince:
          days: 7
      actions:
      - closeIssue
      # Add closure label for tracking
      - addLabel:
          label: Close-Stale
      # Remove triage label as it's no longer needed
      - removeLabel:
          label: Needs-Triage

    - description: Add No-Recent-Activity label to issues that have not had any activity for 7 days
      # First warning stage before closing stale issues
      # Timeline: Day 7 - Add warning label, Day 14 - Close issue if no response
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: Needs-Author-Feedback
      - noActivitySince:
          days: 7
      - isNotLabeledWith:
          label: No-Recent-Activity
      actions:
      # Mark as inactive
      - addLabel:
          label: No-Recent-Activity
      # Notify author with clear timeline for resolution
      - addReply:
          reply: |
                👋 Hello ${issueAuthor},

                We're sending this friendly reminder because we haven't heard back from you in a while and we need more information about this issue to help address it. Please be sure to give us your input within the next **7 days**. If we don't hear back from you within **7 days** of this comment the issue will be automatically closed.

                Thank you for your collaboration!

    - description: Close issues that have not had any activity for 7 days and are labeled with Issue-Addressed
      # Auto-close resolved issues after waiting period for any objections
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: Issue-Addressed
      - noActivitySince:
          days: 7
      actions:
      # Final notification before closure
      - addReply:
          reply: |
                👋 Hello ${issueAuthor},
                
                Since you haven't asked that we "`/unresolve`" the issue, we'll close this out. If you believe further discussion is needed, please add a comment "`/unresolve`" to reopen the issue.

                Thank you for your collaboration!

      # Close the issue after waiting period
      - closeIssue

# ---------------------------------------------------------------------------
# ERROR HANDLING CONFIGURATION
# Defines what happens when policy execution succeeds or fails
# ---------------------------------------------------------------------------
onFailure:
  # Can be configured to notify admins or log errors
onSuccess:
  # Can be configured to perform actions upon successful execution
