# ===========================================================================
# GitHub Repository Issue and Pull Request Management Policy
# ===========================================================================
id: 
name: GitOps.PullRequestIssueManagement
description: Handlers for when an issue is first opened
owner: Arc Jumpstart
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    # ===========================================================================
    # EVENT RESPONDER TASKS
    # Defines automated actions triggered by specific GitHub events
    # ===========================================================================
    eventResponderTasks:
      # ---------------------------------------------------------------------------
      # PULL REQUEST MANAGEMENT
      # Handles PR creation, updates, and empty PRs
      # ---------------------------------------------------------------------------
      - description: >-
          When a PR is opened/updated, if no files are modified
          * Close the issue
          * Add a comment
        if:
          - payloadType: Pull_Request
          - isOpen
          - or:
              - isAction:
                  action: Opened
              - isAction:
                  action: Synchronize
          - filesMatchPattern:
                pattern: ^$
        then:
          - addReply:
              reply: >-
                Hello @${issueAuthor},

                This pull request does not update any files. Please review your commit history and resubmit.

                We will be closing this pull request now!

          - closePullRequest

      - description: When a PR is opened, post a message to the author
        if:
          - payloadType: Pull_Request
          - isAction:
              action: Opened
        then:
          - addReply:
              reply: >-
                Hello @${issueAuthor},

                Thank you for your pull request, A team member will review it soon. All pull requests are validated by the Arc Jumpstart team and must pass all validation checks before being merged.
                By submitting this pull request, you agree that your contributions will be licensed under the [MIT license](https://github.com/microsoft/azure_arc/blob/main/LICENSE-CODE) license and you confirm that you've read and will abide by our [Code of Conduct](https://github.com/microsoft/azure_arc/blob/main/CODE_OF_CONDUCT.md).

      # ---------------------------------------------------------------------------
      # NEW ISSUE MANAGEMENT
      # Handles initial triage and labeling of new issues
      # ---------------------------------------------------------------------------
      - description: When an issue is opened, Identifiy if the issue title contains the word "bug" or "feature" and post a message to the author
        if:
          - payloadType: Issues
          - isAction:
              action: Opened
        then:
          # Add Needs-Triage label to new issues
          - addLabel:
              label: Needs-Triage
          - if:
              # Identifiy if the issue title contains the word "arcbox"
              - titleContains:
                    pattern: "(?i)arcbox"
                    isRegex: true
            then:
                - addLabel:
                    label: ArcBox
          - if:
              # Identifiy if the issue title contains the word "hcibox"
              - titleContains:
                    pattern: "(?i)hcibox"
                    isRegex: true
            then:
                - addLabel:
                    label: HCIBox
          - if:
              # Identifiy if the issue title contains the word "agora"
              - titleContains:
                    pattern: "(?i)agora"
                    isRegex: true
            then:
                - addLabel:
                    label: Agora
          
          - if: 
              # Identifiy if the issue title contains the word "bug"
              - titleContains:
                    pattern: "(?i)bug"
                    isRegex: true
            then:
                # Add Bug-Issue label to issues with the word "bug" in the title
                - addLabel:
                    label: Bug-Issue
                # Add a reply to the issue author
                - addReply:
                    reply: >-
                      Hello @${issueAuthor},

                      Thank you for reporting this issue, A team member will review and triage it soon. All issues are evaluated by the Arc Jumpstart team to determine next steps.
                      By submitting this issue request, you agree that your contributions will be licensed under the project's [MIT license](https://github.com/microsoft/azure_arc/blob/main/LICENSE-CODE) and you confirm that you've read and will abide by our [Code of Conduct](https://github.com/microsoft/azure_arc/blob/main/CODE_OF_CONDUCT.md).          
          - if:
              # Identifiy if the issue title contains the word "feature"
              - titleContains:
                    pattern: "(?i)feature"
                    isRegex: true
            then:
                # Add Feature-Request label to issues with the word "feature" in the title
                - addLabel:
                    label: Feature-Request
                # Add a reply to the feature request author    
                - addReply:
                    reply: >-
                      Hello @${issueAuthor},

                      Thank you for your feature request, A team member will review it soon. All pull requests are validated by the Arc Jumpstart team and must pass all validation checks before being merged.
                      By submitting this pull request, you agree that your contributions will be licensed under the [MIT license](https://github.com/microsoft/azure_arc/blob/main/LICENSE-CODE) license and you confirm that you've read and will abide by our [Code of Conduct](https://github.com/microsoft/azure_arc/blob/main/CODE_OF_CONDUCT.md).

      # ---------------------------------------------------------------------------
      # ISSUE LIFECYCLE MANAGEMENT
      # Handles issue closing, reopening, and duplicate detection
      # ---------------------------------------------------------------------------
      - description: Clear labels when an issue is closed
        triggerOnOwnActions: false
        if:
        - payloadType: Issues
        - isAction:
            action: Closed
        then:
        - removeLabel:
            label: Needs-Triage
        - removeLabel:
            label: Needs-Attention
        - removeLabel: 
            label: Needs-Author-Feedback    
        - addLabel:
            label: Issue-Addressed
        - addReply:
            reply: >-
                Hello @${issueAuthor},

                We've closed this issue because it has been addressed. If you believe further discussion is needed, please add a comment "`/unresolve`" to reopen the issue.    

      - description: Reopen unresolved issues
        triggerOnOwnActions: false
        if:
        - payloadType: Issue_Comment
        - and:
            - commentContains:
                pattern: "(?i)unresolve"
                isRegex: True
        then:
        - removeLabel:
            label: Issue-Addressed
        - removeLabel:
            label: Resolution-Duplicate
        - removeLabel:
            label: No-Recent-Activity
        - addLabel:
            label: Needs-Author-Feedback
        - addReply:
            reply: >-
                Hello @${issueAuthor},

                We've reopened this issue because you marked it as unresolved. We need more information from you or we identified it is not completely resolved. 

        - reopenIssue

      - description: Add needs attention label to reopened issues
        triggerOnOwnActions: false
        if:
        - payloadType: Issues
        - isAction:
            action: Reopened
        then:
        - removeLabel:
            label: Issue-Addressed
        - removeLabel:
            label: Resolution-Duplicate            
        - addLabel:
            label: Needs-Attention
        - addReply:
            reply: >-
                Hello @${issueAuthor},

                We've reopened this issue because we need more information from you or we identified it is not completely resolved.

      - description: Add Resolution-Duplicate label to issues or PRs that are identified as duplicates
        triggerOnOwnActions: false
        if:
        - payloadType: Issue_Comment
        - and:
            - commentContains:
                pattern: "(?i)duplicat(e|ed|ing)?"
                isRegex: True
        then:
        - addReply:
            reply: >-
                Hello @${issueAuthor},

                We've identified this as a duplicate of another issue or PR that already exists. This specific instance is being closed in favor of the linked issue. Please add your ðŸ‘ to the other issue to raise its priority. Thanks for your contribution!

        - closeIssue
        - removeLabel:
            label: Needs-Triage
        - removeLabel:
            label: Needs-Attention
        - removeLabel:
            label: Needs-Feedback-Hub
        - removeLabel:
            label: Needs-Author-Feedback
        - addLabel:
            label: Resolution-Duplicate
 
    # ===========================================================================
    # SCHEDULED SEARCHES
    # Periodic tasks that run on defined schedules
    # ===========================================================================
    scheduledSearches:
    - description: Close stale issues
      frequencies:
      - daily:
          time: 1:0      # Runs at 1:00 AM daily
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: Needs-Author-Feedback
      - hasLabel:
          label: No-Recent-Activity
      - noActivitySince:
          days: 21       # 3 weeks of inactivity
      actions:
      - closeIssue
      
    - description: Add no recent activity label to issues
      frequencies:
      - hourly:
          hour: 6        # Runs at 6:00 every hour
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: Needs-Author-Feedback
      - noActivitySince:
          days: 7        # 1 week of inactivity
      - isNotLabeledWith:
          label: No-Recent-Activity
      actions:
      - addLabel:
          label: No-Recent-Activity
      - addReply:
          reply: >-
            Hello @${issueAuthor}, 
            
            We're sending this friendly reminder because we haven't heard back from you in a while and we need more information about this issue to help address it. Please be sure to give us your input within the next **7 days**. If we don't hear back from you within **14 days** of this comment the issue will be automatically closed. Thank you!
          
    - description: '[Resolve Workflow] Close Addressed Issues'
      frequencies:
      - hourly:
          hour: 6        # Runs at 6:00 every hour
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: Issue-Addressed
      - noActivitySince:
          days: 7        # 1 week of inactivity
      actions:
      - addReply: 
          reply: >-
          
            Hello @${issueAuthor}, 
            
            Since you haven't asked that we "`/unresolve`" the issue, we'll close this out. If you believe further discussion is needed, please add a comment "`/unresolve`" to reopen the issue.

      - closeIssue

# Configuration for handling failures or success events
onFailure:
onSuccess:
