tput setaf 1;echo "-----------------------------------------------------------------------------------------------------------------------------"
echo ""
tput setaf 6;echo "Welcome to the Jumpstart Azure Arc-enabled data services Cluster API (CAPI) Kubernetes cluster!"
echo ""
tput setaf 6;echo "* To check the CAPI deployment log, use the 'cat jumpstart_logs/installCAPI.log' command."
echo ""
tput setaf 6;echo "* This deployment log can also be found in your scenario deployment Azure resource group storage account container."
echo ""
tput setaf 6;echo "* To work with the CAPI Kubernetes cluster, use the 'kubectl <command>'. For example: kubectl get nodes"
echo ""
tput setaf 1;echo "-----------------------------------------------------------------------------------------------------------------------------"