# ==========================================================================
# ARCDATA-INSTALLER
# --------------------------------------------------------------------------
# Service account used by Bootstrapper Helm Chart for installation of Arc-
# enabled Data services.
# --------------------------------------------------------------------------
# VAR SUBSTITUTIONS
# --------------------------------------------------------------------------
# - {{AZURE_ARC_NAMESPACE}}: namespace for ConnectedK8s operators
# - {{DATA_CONTROLLER_NAMESPACE}}: namespace for Azure Arc-enabled Data Services
# - {{ARCDATA_INSTALLER_SERVICE_ACCOUNT}}: name of the installer service account
# ==========================================================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ARCDATA_INSTALLER_SERVICE_ACCOUNT}}
  namespace: {{DATA_CONTROLLER_NAMESPACE}}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: arcdata-installer-role
  namespace: {{DATA_CONTROLLER_NAMESPACE}}
rules:
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  # --------------------------------------------------------------------------
  # Extension installer service account manages the helm release secret
  # (sh.helm.release.v1.extension-name.v1) on the Data Services Namespace
  # --------------------------------------------------------------------------
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - ""
  # --------------------------------------------------------------------------
  resources:
  - configmaps
  verbs:
  - create
  - get
  - delete
  - list
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - delete
  - patch
- apiGroups:
  - arcdata.microsoft.com
  resources:
  - datacontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{DATA_CONTROLLER_NAMESPACE}}:cr-arcdata-installer
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - list
  - get
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resourceNames:
  - activedirectoryconnectors.arcdata.microsoft.com
  - datacontrollers.arcdata.microsoft.com
  - exporttasks.tasks.arcdata.microsoft.com
  - failovergroups.sql.arcdata.microsoft.com
  - kafkas.arcdata.microsoft.com
  - monitors.arcdata.microsoft.com
  - postgresqlrestoretasks.tasks.postgresql.arcdata.microsoft.com
  - postgresqls.arcdata.microsoft.com
  - sqlmanagedinstancemonitoringprofiles.arcdata.microsoft.com
  - sqlmanagedinstancereprovisionreplicatasks.tasks.sql.arcdata.microsoft.com
  - sqlmanagedinstancerestoretasks.tasks.sql.arcdata.microsoft.com
  - sqlmanagedinstances.sql.arcdata.microsoft.com
  - telemetrycollectors.arcdata.microsoft.com
  - telemetryrouters.arcdata.microsoft.com
  resources:
  - customresourcedefinitions
  verbs:
  - update
  - patch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - create
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - delete
  - get
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - create
  - patch
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - create
  - patch
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - delete
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - ""
  resources:
  - nodes/stats
  - nodes/proxy
  - pods
  verbs:
  - list
  - get

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{DATA_CONTROLLER_NAMESPACE}}:crb-arcdata-installer
subjects:
- kind: ServiceAccount
  name: {{ARCDATA_INSTALLER_SERVICE_ACCOUNT}}
  namespace: {{DATA_CONTROLLER_NAMESPACE}}
roleRef:
  kind: ClusterRole
  name: {{DATA_CONTROLLER_NAMESPACE}}:cr-arcdata-installer
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arcdata-installer-role-binding
  namespace: {{DATA_CONTROLLER_NAMESPACE}}
subjects:
- kind: ServiceAccount
  name: {{ARCDATA_INSTALLER_SERVICE_ACCOUNT}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: arcdata-installer-role

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: arcdata-installer-role
  namespace: {{AZURE_ARC_NAMESPACE}}
rules:
  # --------------------------------------------------------------------------
  # During Helm install, Openshift namespace patcher requires ability to spin up
  # Jobs in azure-arc namespace
  # --------------------------------------------------------------------------
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - delete
  # --------------------------------------------------------------------------

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arcdata-installer-role-binding
  namespace: {{AZURE_ARC_NAMESPACE}}
subjects:
- kind: ServiceAccount
  name: {{ARCDATA_INSTALLER_SERVICE_ACCOUNT}}
  namespace: {{DATA_CONTROLLER_NAMESPACE}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: arcdata-installer-role
