# Replace these placeholders with the actual values before applying
# - {{NAMESPACE}}: namespace for Azure Arc-enabled Data Services below
# - {{INSTALLER_SERVICE_ACCOUNT}}: name of the installer service account

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: arcdata-installer-role
rules:
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - create
  - get
  - delete
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - delete
- apiGroups:
  - arcdata.microsoft.com
  resources:
  - datacontrollers
  verbs:
  - create
  - delete
  - get
  - list

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{NAMESPACE}}:cr-arcdata-installer
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - list
  - get
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resourceNames:
  - activedirectoryconnectors.arcdata.microsoft.com
  - sqlmanagedinstancemonitoringprofiles.arcdata.microsoft.com
  - datacontrollers.arcdata.microsoft.com
  - exporttasks.tasks.arcdata.microsoft.com
  - failovergroups.sql.arcdata.microsoft.com
  - kafkas.arcdata.microsoft.com
  - monitors.arcdata.microsoft.com
  - telemetrycollectors.arcdata.microsoft.com
  - postgresqls.arcdata.microsoft.com
  - sqlmanagedinstancerestoretasks.tasks.sql.arcdata.microsoft.com
  - sqlmanagedinstances.sql.arcdata.microsoft.com
  - telemetryrouters.arcdata.microsoft.com
  resources:
  - customresourcedefinitions
  verbs:
  - update
  - patch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - create
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - delete
  - get
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - create
  - patch
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - create
  - patch
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - delete
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - list
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - patch
- apiGroups:
  - ""
  resources:
  - nodes/stats
  - nodes/proxy
  - pods
  verbs:
  - list
  - get

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{NAMESPACE}}:crb-arcdata-installer
subjects:
- kind: ServiceAccount
  name: {{INSTALLER_SERVICE_ACCOUNT}}
  namespace: {{NAMESPACE}}
roleRef:
  kind: ClusterRole
  name: {{NAMESPACE}}:cr-arcdata-installer
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arcdata-installer-role-binding
subjects:
- kind: ServiceAccount
  name: {{INSTALLER_SERVICE_ACCOUNT}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: arcdata-installer-role