# ==========================================================================
# AZURE-ARC-EXTENSION-IDENTITY
# --------------------------------------------------------------------------
# Custom Resource Definition used to give our extension an identity in Azure
# --------------------------------------------------------------------------
# VAR SUBSTITUTIONS
# --------------------------------------------------------------------------
# - {{AZURE_ARC_NAMESPACE}}: namespace for ConnectedK8s operators
# - {{DATA_CONTROLLER_NAMESPACE}}: namespace for Azure Arc-enabled Data Services
# - {{ARCDATA_INSTALLER_SERVICE_ACCOUNT}}: name of the installer service account
# ==========================================================================

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{DATA_CONTROLLER_NAMESPACE}}:cr-extension-identity
rules:
- apiGroups:
  - clusterconfig.azure.com
  resources:
  - azureextensionidentities
  verbs:
  - create
  - delete
  - get
  - list
  - patch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{DATA_CONTROLLER_NAMESPACE}}:crb-extension-identity
  namespace: {{AZURE_ARC_NAMESPACE}}
subjects:
- kind: ServiceAccount
  name: {{ARCDATA_INSTALLER_SERVICE_ACCOUNT}}
  namespace: {{DATA_CONTROLLER_NAMESPACE}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{DATA_CONTROLLER_NAMESPACE}}:cr-extension-identity
