apiVersion: mq.iotoperations.azure.com/v1beta1
kind: BrokerListener
metadata:
  name: "az-mqtt-non-tls-listener"
spec:
  brokerRef: "my-broker"
  serviceType: loadBalancer
  authenticationEnabled: false
  authorizationEnabled: false
  port: 1883