
name: model-env

dependencies:
  - python=3.6.2

  - pip:
    - azureml-dataset-runtime[pandas,fuse]~=1.24.0.0
    - azureml-defaults~=1.24.0.0
    - scikit-learn==0.22.1

channels:
  - anaconda
  - conda-forge
