name: tutorial-env
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.6.2
  - pip:
      - 'azureml-dataset-runtime[pandas,fuse]~=1.26.0.0'
      - azureml-defaults~=1.26.0.0
  - scikit-learn==0.22.1