apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  type: LoadBalancer
  selector:
    app: influxdb
  ports:
  - name: api
    port: 9999
    protocol: TCP
    targetPort: 9999
  - name: gui
    port: 8086
    protocol: TCP
    targetPort: 8086