apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: DataflowEndpoint
metadata:
  name: mq
spec:
  endpointType: mqtt
  authentication:
    method: serviceAccountToken
    serviceAccountTokenSettings:
      audience: aio-mqtt
  mqttSettings:
    {}
---
apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: DataflowEndpoint
metadata:
  name: eventgrid
spec:
  endpointType: mqtt
  authentication:
    method: systemAssignedManagedIdentity
    systemAssignedManagedIdentitySettings:
      audience: https://eventgrid.azure.net
  mqttSettings:
    host: eventGridPlaceholder:8883
    tls:
      mode: Enabled
---
apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: Dataflow
metadata:
  name: my-dataflow
spec:
  profileRef: my-dataflow-profile
  mode: enabled
  operations:
  - operationType: source
    name: source1
    sourceSettings:
      endpointRef: mq
      dataSources:
        - "topic/#"
        - azure-iot-operations/data/#
  - operationType: destination
    name: destination1
    destinationSettings:
      endpointRef: eventgrid
      dataDestination: factory
---
apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: DataflowProfile
metadata:
  name: my-dataflow-profile
spec:
  instanceCount: 2