name: promote-to-canary
on:
  repository_dispatch:
    types:
      - HelmRelease/pos.contoso-supermarket
      - Kustomization/config-supermarket-pos.contoso-supermarket

permissions:
  contents: write
  pull-requests: write

jobs:
  promote-to-canary:
    runs-on: ubuntu-latest
    if: |
      github.event.client_payload.metadata.summary == 'env=staging' &&
      github.event.client_payload.severity == 'info' && [[github.event.client_payload.message =~ "Health check passed" ]]

    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v3

    - name: Run tests
      uses: mscoutermarsh/ascii-art-action@master
      with:
        text: 'Testing complete!'

    - name: 'Login to ACR'
      uses: azure/docker-login@v1
      with:
        login-server: "${{ secrets.ACR_NAME }}.azurecr.io"
        username: ${{ secrets.SPN_CLIENT_ID }}
        password: ${{ secrets.SPN_CLIENT_SECRET }}

    - name: Increment Image Tag
      id: latestImageTag
      env:
        ACR_NAME: ${{ secrets.ACR_NAME }}
        namespace: "staging"
      run: |
        az login --service-principal --username ${{ secrets.SPN_CLIENT_ID }} --password ${{ secrets.SPN_CLIENT_SECRET }} --tenant ${{ secrets.SPN_TENANT_ID }}
        LATEST_TAG=$(az acr repository show-tags --name $ACR_NAME --repository $namespace/contoso-supermarket/pos --orderby time_desc --top 1 --output tsv)
        NEW_VERSION=$(echo $LATEST_TAG | awk -F. '{$NF = $NF + 1;} 1' OFS=.)
        echo $NEW_VERSION
        echo "latest_tag=$NEW_VERSION" >> $GITHUB_OUTPUT

    - name: 'Build and push new images'
      env:
        latest_tag: ${{ steps.latestImageTag.outputs.latest_tag }}
        namespace: "canary"
      run: |
        docker build ./contoso_supermarket/developer/pos/src -t "${{ secrets.ACR_NAME }}.azurecr.io/$namespace/contoso-supermarket/pos:$latest_tag"
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/$namespace/contoso-supermarket/pos:$latest_tag

    - name: 'Checkout canary branch'
      uses: actions/checkout@v3
      with:
        ref: 'canary'

    - name: 'Update Image tag on canary branch and submit PR'
      env:
        latest_tag: ${{ steps.latestImageTag.outputs.latest_tag }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        FILE_PATH=$(find . -name "chicago.yaml")
        newLine="    image_tag: $latest_tag"
        if [ ! -z "$FILE_PATH" ]; then
          sed -i "s/.*image_tag.*/$newLine/" $FILE_PATH
        else
          echo "chicago.yaml not found"
        fi
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git checkout -b update-canary-image-tag canary
        git config pull.rebase false
        git add --all
        git commit -m "Update Image Tag on Canary to $latest_tag"
        git push --set-upstream origin update-canary-image-tag
        gh pr create --title "Update Canary Image Tag to $latest_tag" --body "Update Canary Image Tag to $latest_tag"

