name: Update-helm-values

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  replace-text:
    if: ${{ github.repository != 'microsoft/jumpstart-agora-apps' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Replace the correct ACR name
      continue-on-error: true
      env:
        ACR_NAME: ${{ secrets.ACR_NAME }}
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git pull
        branches=("production.yaml" "staging.yaml" "canary.yaml" "main.yaml")
        for branch in "${branches[@]}"; do
          FILE_PATH=$(find . -name $branch)
          newLine="    acr_name: $ACR_NAME"
          if [ ! -z "$FILE_PATH" ]; then
            sed -i "s/.*acr_name.*/$newLine/" $FILE_PATH
          else
            echo "$branch not found"
          fi
        done

        # Push changes
        git add .
        git commit -m "Update ACR name"
        git push

    - name: Replace the correct image tag
      continue-on-error: true
      env:
        IMAGE_TAG: "v1.0"
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git pull

        branches=("production.yaml" "staging.yaml" "canary.yaml" "main.yaml")
        for branch in "${branches[@]}"; do
          FILE_PATH=$(find . -name $branch)
          newLine="    image_tag: $IMAGE_TAG"
          if [ ! -z $FILE_PATH ]; then
            sed -i "s/.*image_tag.*/$newLine/" $FILE_PATH
          else
            echo "$branch not found"
          fi
        done

        # Push changes
        git add .
        git commit -m "Update ACR name"
        git push

    - name: Replace the correct Cosmos DB endpoint
      continue-on-error: true
      env:
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        COSMOS_ENDPOINT: ${{ secrets.COSMOS_DB_ENDPOINT }}
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git pull

        branches=("production.yaml" "staging.yaml" "canary.yaml" "main.yaml")
        for branch in "${branches[@]}"; do
          FILE_PATH=$(find . -name $branch)
          newLine="      endpoint: $COSMOS_ENDPOINT"
          if [ ! -z "$FILE_PATH" ]; then
            sed -i "s#.*endpoint.*#$newLine#" $FILE_PATH
          else
            echo "$branch not found"
          fi
        done

        # Push changes
        git add .
        git commit -m "Update Cosmos DB endpoint"
        git push

    - name: Replace the correct GitHub account
      continue-on-error: true
      env:
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        COSMOS_ENDPOINT: ${{ secrets.COSMOS_DB_ENDPOINT }}
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git pull

        branches=("production.yaml" "staging.yaml" "canary.yaml" "main.yaml")
        for branch in "${branches[@]}"; do
          FILE_PATH=$(find . -name $branch)
          newLine="    github_User: $GITHUB_REPOSITORY_OWNER"
          if [ ! -z "$FILE_PATH" ]; then
            sed -i "s#.*github_User.*#$newLine#" $FILE_PATH
          else
            echo "$branch not found"
          fi
        done

        # Push changes
        git add .
        git commit -m "Update GitHub account"
        git push