name: Update ACR and Cosmos DB values in all branches

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  replace-text:
    if: ${{ github.repository != 'microsoft/jumpstart-agora-apps' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Replace text and commit changes
      run: |
        SEARCH_TEXT="old-text"
        REPLACE_TEXT="new-text"
        FILE_PATTERN="*.txt"
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        for branch in $(git branch -r | grep -v HEAD); do
          git checkout "${branch#origin/}"
          git pull
          find . -type f -name "$FILE_PATTERN" -exec sed -i "s/$SEARCH_TEXT/$REPLACE_TEXT/g" {} +
          git add -u
          git diff --quiet && git diff --staged --quiet || git commit -m "Replace text in files"
          git push
        done

    - name: Replace variables with the correct names
      env:
        ACR_NAME: ${{ secrets.ACR_NAME }}
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        COSMOS_ENDPOINT: ${{ secrets.COSMOS_DB_ENDPOINT }}
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        for branch in $(git branch -r | grep -v HEAD); do
          git checkout "${branch#origin/}"
          git pull
          # Update ACR name
          FILE_PATH=$(find . -name "staging.yaml")
          newLine="    acr_name: $ACR_NAME"
          if [ ! -z "$FILE_PATH" ]; then
            sed -i "s/.*acr_name.*/$newLine/" $FILE_PATH
          else
            echo "staging.yaml not found"
          fi

          FILE_PATH=$(find . -name "chicago.yaml")
          newLine="    acr_name: $ACR_NAME"
          if [ ! -z "$FILE_PATH" ]; then
            sed -i "s/.*acr_name.*/$newLine/" $FILE_PATH
          else
            echo "chicago.yaml not found"
          fi

          FILE_PATH=$(find . -name "seattle.yaml")
          newLine="    acr_name: $ACR_NAME"
          if [ ! -z "$FILE_PATH" ]; then
            sed -i "s/.*acr_name.*/$newLine/" $FILE_PATH
          else
            echo "seattle.yaml not found"
          fi

          FILE_PATH=$(find . -name "dev.yaml")
          newLine="    acr_name: $ACR_NAME"
          if [ ! -z "$FILE_PATH" ]; then
            sed -i "s/.*acr_name.*/$newLine/" $FILE_PATH
          else
            echo "dev.yaml not found"
          fi
          # Update GitHub account in Chart.yaml
          find . -type f -name "Chart.yaml" -print0 | xargs -0 sed -i "s/__github_account__/$GITHUB_REPOSITORY_OWNER/g"

          # Update Cosmos DB endpoint
          FILE_PATH=$(find . -name "staging.yaml")
          newLine="      endpoint: $COSMOS_ENDPOINT"
          if [ ! -z "$FILE_PATH" ]; then
            sed -i "s#.*endpoint.*#$newLine#" $FILE_PATH
          else
            echo "staging.yaml not found"
          fi

          FILE_PATH=$(find . -name "chicago.yaml")
          newLine="      endpoint: $COSMOS_ENDPOINT"
          if [ ! -z "$FILE_PATH" ]; then
            sed -i "s#.*endpoint.*#$newLine#" $FILE_PATH
          else
            echo "chicago.yaml not found"
          fi

          FILE_PATH=$(find . -name "seattle.yaml")
          newLine="      endpoint: $COSMOS_ENDPOINT"
          if [ ! -z "$FILE_PATH" ]; then
            sed -i "s#.*endpoint.*#$newLine#" $FILE_PATH
          else
            echo "seattle.yaml not found"
          fi

          FILE_PATH=$(find . -name "dev.yaml")
          newLine="      endpoint: $COSMOS_ENDPOINT"
          if [ ! -z "$FILE_PATH" ]; then
            sed -i "s#.*endpoint.*#$newLine#" $FILE_PATH
          else
            echo "dev.yaml not found"
          fi
          git add -u
          git diff --quiet && git diff --staged --quiet || git commit -m "Replace text in files"
          git push
        done