name: Feature Request
description: Suggest an idea or enhancement for Arc Jumpstart
title: "[Feature Request]: "
labels: ["Feature-Request", "Needs-Triage"]
projects: ["microsoft/162"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

        If your feature request is related to documentation, we kindly ask you to submit it in our [documentation repository](https://github.com/Azure/arc_jumpstart_docs).

        The intent of this "Feature Request" template is to address feature requests related to the various Arc Jumpstart solutions. The Arc Jumpstart team does not handle and/or support Azure Arc upstream core product related features and will try to assist on a best effort basis. For a core product feature request/feedback, please submit through [general feedback](https://feedback.azure.com).
  - type: checkboxes
    id: solution
    attributes:
      label: Jumpstart Solution
      description: Which Jumpstart solution is this feature request for?
      options:
        - label: Jumpstart ArcBox
        - label: Jumpstart LocalBox
        - label: Jumpstart Agora
        - label: A specific Jumpstart scenario
        - label: Jumpstart Drops
        - label: Something else
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What problem does this feature solve? Why is it needed?
      placeholder: Describe the use case and value this feature would bring.
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you think this should be implemented?
      placeholder: Describe your suggested approach to implementing this feature.
    validations:
      required: false
  - type: input
    id: solution-url
    attributes:
      label: We need a URL
      description: Share with us the URL to the Jumpstart solution related to your feature request.
      placeholder: ex. https://jumpstart.azure.com/azure_jumpstart_arcbox/ITPro
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Any other information that might help us understand your request.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this feature request, you agree to follow our [Code of Conduct](https://github.com/Azure/arc_jumpstart_docs/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
