apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kafkas.arcdata.microsoft.com
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  group: arcdata.microsoft.com
  versions:
  - name: v1beta1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Status
      type: string
      jsonPath: ".status.state"
    - name: Age
      type: date
      jsonPath: ".metadata.creationTimestamp"
  - name: v1beta2
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Status
      type: string
      jsonPath: ".status.state"
    - name: Age
      type: date
      jsonPath: ".metadata.creationTimestamp"
  - name: v1beta3
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              kraftControllerMode:
                type: string
                enum:
                - Combined
                - Separate
              broker:
                type: object
                properties:
                  requests:
                    type: object
                    properties:
                      vcores:
                        type: integer
                      memory:
                        type: string
                  limits:
                    type: object
                    properties:
                      vcores:
                        type: integer
                      memory:
                        type: string
                  storage:
                    type: object
                    properties:
                      data:
                        type: object
                        properties:
                          className:
                            type: string
                          labels:
                            type: object
                            additionalProperties:
                              type: string
                          annotations:
                            type: object
                            additionalProperties:
                              type: string
                          accessMode:
                            type: string
                          size:
                            type: string
                          claimName:
                            type: string
                      logs:
                        type: object
                        properties:
                          className:
                            type: string
                          labels:
                            type: object
                            additionalProperties:
                              type: string
                          annotations:
                            type: object
                            additionalProperties:
                              type: string
                          accessMode:
                            type: string
                          size:
                            type: string
                          claimName:
                            type: string
                  replicas:
                    type: integer
              security:
                type: object
                properties:
                  superUsers:
                    type: array
                    items:
                      type: string
              update:
                type: object
                properties:
                  desiredVersion:
                    type: string
          status:
            type: object
            properties:
              readyReplicas:
                type: string
              observedGeneration:
                type: integer
              runningVersion:
                type: string
              registryVersions:
                type: object
                properties:
                  next:
                    type: string
                  previous:
                    type: string
                  current:
                    type: string
                  latest:
                    type: string
                  behind:
                    type: integer
                  available:
                    type: array
                    items:
                      type: string
              releasedVersions:
                type: object
                properties:
                  next:
                    type: string
                  previous:
                    type: string
                  current:
                    type: string
                  latest:
                    type: string
                  behind:
                    type: integer
                  available:
                    type: array
                    items:
                      type: string
              arcDataServicesK8sExtensionLatestVersion:
                type: string
              endpoints:
                type: object
                additionalProperties:
                  type: string
              state:
                type: string
              healthState:
                type: string
              reason:
                type: string
              message:
                type: string
              lastUpdateTime:
                type: string
                format: date-time
          apiVersion:
            type: string
          kind:
            type: string
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Status
      type: string
      jsonPath: ".status.state"
    - name: Age
      type: date
      jsonPath: ".metadata.creationTimestamp"
  - name: v1beta4
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              kraftControllerMode:
                type: string
                enum:
                - Combined
                - Separate
              broker:
                type: object
                properties:
                  resources:
                    type: object
                    properties:
                      limits:
                        type: object
                        additionalProperties:
                          type: object
                      requests:
                        type: object
                        additionalProperties:
                          type: object
                  heap:
                    type: object
                    properties:
                      Xmx:
                        type: string
                      Xms:
                        type: string
                  storage:
                    type: object
                    properties:
                      data:
                        type: object
                        properties:
                          className:
                            type: string
                          labels:
                            type: object
                            additionalProperties:
                              type: string
                          annotations:
                            type: object
                            additionalProperties:
                              type: string
                          accessMode:
                            type: string
                          size:
                            type: string
                          claimName:
                            type: string
                      logs:
                        type: object
                        properties:
                          className:
                            type: string
                          labels:
                            type: object
                            additionalProperties:
                              type: string
                          annotations:
                            type: object
                            additionalProperties:
                              type: string
                          accessMode:
                            type: string
                          size:
                            type: string
                          claimName:
                            type: string
                  replicas:
                    type: integer
              controller:
                type: object
                properties:
                  resources:
                    type: object
                    properties:
                      limits:
                        type: object
                        additionalProperties:
                          type: object
                      requests:
                        type: object
                        additionalProperties:
                          type: object
                  heap:
                    type: object
                    properties:
                      Xmx:
                        type: string
                      Xms:
                        type: string
                  storage:
                    type: object
                    properties:
                      data:
                        type: object
                        properties:
                          className:
                            type: string
                          labels:
                            type: object
                            additionalProperties:
                              type: string
                          annotations:
                            type: object
                            additionalProperties:
                              type: string
                          accessMode:
                            type: string
                          size:
                            type: string
                          claimName:
                            type: string
                      logs:
                        type: object
                        properties:
                          className:
                            type: string
                          labels:
                            type: object
                            additionalProperties:
                              type: string
                          annotations:
                            type: object
                            additionalProperties:
                              type: string
                          accessMode:
                            type: string
                          size:
                            type: string
                          claimName:
                            type: string
                  replicas:
                    type: integer
              server:
                type: object
                properties:
                  resources:
                    type: object
                    properties:
                      limits:
                        type: object
                        additionalProperties:
                          type: object
                      requests:
                        type: object
                        additionalProperties:
                          type: object
                  heap:
                    type: object
                    properties:
                      Xmx:
                        type: string
                      Xms:
                        type: string
                  storage:
                    type: object
                    properties:
                      data:
                        type: object
                        properties:
                          className:
                            type: string
                          labels:
                            type: object
                            additionalProperties:
                              type: string
                          annotations:
                            type: object
                            additionalProperties:
                              type: string
                          accessMode:
                            type: string
                          size:
                            type: string
                          claimName:
                            type: string
                      logs:
                        type: object
                        properties:
                          className:
                            type: string
                          labels:
                            type: object
                            additionalProperties:
                              type: string
                          annotations:
                            type: object
                            additionalProperties:
                              type: string
                          accessMode:
                            type: string
                          size:
                            type: string
                          claimName:
                            type: string
                  replicas:
                    type: integer
              security:
                type: object
                properties:
                  superUsers:
                    type: array
                    items:
                      type: string
              update:
                type: object
                properties:
                  desiredVersion:
                    type: string
          status:
            type: object
            properties:
              readyReplicas:
                type: string
              observedGeneration:
                type: integer
              runningVersion:
                type: string
              registryVersions:
                type: object
                properties:
                  next:
                    type: string
                  previous:
                    type: string
                  current:
                    type: string
                  latest:
                    type: string
                  behind:
                    type: integer
                  available:
                    type: array
                    items:
                      type: string
              releasedVersions:
                type: object
                properties:
                  next:
                    type: string
                  previous:
                    type: string
                  current:
                    type: string
                  latest:
                    type: string
                  behind:
                    type: integer
                  available:
                    type: array
                    items:
                      type: string
              arcDataServicesK8sExtensionLatestVersion:
                type: string
              endpoints:
                type: object
                additionalProperties:
                  type: string
              state:
                type: string
              healthState:
                type: string
              reason:
                type: string
              message:
                type: string
              lastUpdateTime:
                type: string
                format: date-time
          apiVersion:
            type: string
          kind:
            type: string
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Status
      type: string
      jsonPath: .status.state
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  conversion:
    strategy: None
  names:
    kind: Kafka
    plural: kafkas
    shortNames:
    - kafka
  scope: Namespaced
