{{ if and (not .Values.Azure.LeastPrivilegeSettings.InstallerServiceAccount) (not .Values.systemDefaultValues.installerServiceAccount) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: sa-arc-webhook-job
  namespace: {{ .Release.Namespace }}
{{ end }}