apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sqlmanagedinstancemonitoringprofiles.arcdata.microsoft.com
  annotations:
    helm.sh/resource-policy: keep
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  group: arcdata.microsoft.com
  versions:
  - name: v1beta1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              datasets:
                type: object
                properties:
                  activeSessions:
                    type: object
                    properties:
                      frequency:
                        type: string
                  cpuUtilization:
                    type: object
                    properties:
                      frequency:
                        type: string
                  databaseProperties:
                    type: object
                    properties:
                      frequency:
                        type: string
                  databaseReplicas:
                    type: object
                    properties:
                      frequency:
                        type: string
                  databaseStorageUtilization:
                    type: object
                    properties:
                      frequency:
                        type: string
                  healthDiagnostics:
                    type: object
                    properties:
                      frequency:
                        type: string
                  memoryUtilization:
                    type: object
                    properties:
                      frequency:
                        type: string
                  performanceCounters:
                    type: object
                    properties:
                      frequency:
                        type: string
                  serverProperties:
                    type: object
                    properties:
                      frequency:
                        type: string
                  queryRuntimeStats:
                    type: object
                    properties:
                      frequency:
                        type: string
                  queryWaitStats:
                    type: object
                    properties:
                      frequency:
                        type: string
                  sqlAgentJobHistory:
                    type: object
                    properties:
                      frequency:
                        type: string
                  sqlAgentJobState:
                    type: object
                    properties:
                      frequency:
                        type: string
                  storageIo:
                    type: object
                    properties:
                      frequency:
                        type: string
                  volumeStorageUtilization:
                    type: object
                    properties:
                      frequency:
                        type: string
                  waitStats:
                    type: object
                    properties:
                      frequency:
                        type: string
              xevents:
                type: object
          status:
            type: object
            properties:
              observedGeneration:
                type: integer
              runningVersion:
                type: string
              registryVersions:
                type: object
                properties:
                  next:
                    type: string
                  previous:
                    type: string
                  current:
                    type: string
                  latest:
                    type: string
                  behind:
                    type: integer
                  available:
                    type: array
                    items:
                      type: string
              releasedVersions:
                type: object
                properties:
                  next:
                    type: string
                  previous:
                    type: string
                  current:
                    type: string
                  latest:
                    type: string
                  behind:
                    type: integer
                  available:
                    type: array
                    items:
                      type: string
              arcDataServicesK8sExtensionLatestVersion:
                type: string
              endpoints:
                type: object
                additionalProperties:
                  type: string
              state:
                type: string
              healthState:
                type: string
              reason:
                type: string
              message:
                type: string
              lastUpdateTime:
                type: string
                format: date-time
          apiVersion:
            type: string
          kind:
            type: string
    subresources:
      status: {}
    additionalPrinterColumns:
    - jsonPath: .status.state
      name: Status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
  - name: v1beta2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              datasets:
                type: object
                properties:
                  activeSessions:
                    type: object
                    properties:
                      frequency:
                        type: string
                  cpuUtilization:
                    type: object
                    properties:
                      frequency:
                        type: string
                  databaseProperties:
                    type: object
                    properties:
                      frequency:
                        type: string
                  databaseReplicas:
                    type: object
                    properties:
                      frequency:
                        type: string
                  databaseStorageUtilization:
                    type: object
                    properties:
                      frequency:
                        type: string
                  healthDiagnostics:
                    type: object
                    properties:
                      frequency:
                        type: string
                  memoryUtilization:
                    type: object
                    properties:
                      frequency:
                        type: string
                  performanceCounters:
                    type: object
                    properties:
                      frequency:
                        type: string
                  serverProperties:
                    type: object
                    properties:
                      frequency:
                        type: string
                  queryRuntimeStats:
                    type: object
                    properties:
                      frequency:
                        type: string
                  queryWaitStats:
                    type: object
                    properties:
                      frequency:
                        type: string
                  sqlAgentJobHistory:
                    type: object
                    properties:
                      frequency:
                        type: string
                  sqlAgentJobState:
                    type: object
                    properties:
                      frequency:
                        type: string
                  storageIo:
                    type: object
                    properties:
                      frequency:
                        type: string
                  volumeStorageUtilization:
                    type: object
                    properties:
                      frequency:
                        type: string
                  waitStats:
                    type: object
                    properties:
                      frequency:
                        type: string
              xevents:
                description: List of Extended Events sessions to collect.
                type: array
                items:
                  type: object
                  properties:
                    name:
                      description: The name of the Extended Events session.
                      type: string
                    target:
                      type: object
                      properties:
                        type:
                          description: The target type.
                          type: string
                          enum:
                          - None
                          - EventFile
                        filename:
                          description: 'For EventFile targets, this is the filename
                            without a path (e.g: "MySessionFile.xel").'
                          type: string
          status:
            type: object
            properties:
              observedGeneration:
                type: integer
              runningVersion:
                type: string
              registryVersions:
                type: object
                properties:
                  next:
                    type: string
                  previous:
                    type: string
                  current:
                    type: string
                  latest:
                    type: string
                  behind:
                    type: integer
                  available:
                    type: array
                    items:
                      type: string
              releasedVersions:
                type: object
                properties:
                  next:
                    type: string
                  previous:
                    type: string
                  current:
                    type: string
                  latest:
                    type: string
                  behind:
                    type: integer
                  available:
                    type: array
                    items:
                      type: string
              arcDataServicesK8sExtensionLatestVersion:
                type: string
              endpoints:
                type: object
                additionalProperties:
                  type: string
              state:
                type: string
              healthState:
                type: string
              reason:
                type: string
              message:
                type: string
              lastUpdateTime:
                type: string
                format: date-time
          apiVersion:
            type: string
          kind:
            type: string
    subresources:
      status: {}
    additionalPrinterColumns:
    - jsonPath: .status.state
      name: Status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
  names:
    kind: SqlManagedInstanceMonitoringProfile
    plural: sqlmanagedinstancemonitoringprofiles
  scope: Namespaced
