apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sqlmanagedinstancerestoretasks.tasks.sql.arcdata.microsoft.com
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  group: tasks.sql.arcdata.microsoft.com
  versions:
  - name: v1beta1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - jsonPath: .status.state
      name: Status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - jsonPath: .status.state
      name: Status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
  conversion:
    strategy: None
  names:
    kind: SqlManagedInstanceRestoreTask
    singular: sqlmanagedinstancerestoretask
    plural: sqlmanagedinstancerestoretasks
    shortNames:
      - sqlmirestoretask
  scope: Namespaced
