apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sqlmanagedinstances.sql.arcdata.microsoft.com
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  group: sql.arcdata.microsoft.com
  versions:
  - name: v1beta1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Status
      type: string
      jsonPath: ".status.state"
    - name: Replicas
      type: string
      jsonPath: ".status.readyReplicas"
    - name: Primary-Endpoint
      type: string
      jsonPath: ".status.primaryEndpoint"
    - name: Age
      type: date
      jsonPath: ".metadata.creationTimestamp"
  - name: v1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Status
      type: string
      jsonPath: ".status.state"
    - name: Replicas
      type: string
      jsonPath: ".status.readyReplicas"
    - name: Primary-Endpoint
      type: string
      jsonPath: ".status.primaryEndpoint"
    - name: Age
      type: date
      jsonPath: ".metadata.creationTimestamp"
  - name: v2
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Status
      type: string
      jsonPath: ".status.state"
    - name: Replicas
      type: string
      jsonPath: ".status.readyReplicas"
    - name: Primary-Endpoint
      type: string
      jsonPath: ".status.primaryEndpoint"
    - name: Age
      type: date
      jsonPath: ".metadata.creationTimestamp"
  - name: v3
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Status
      type: string
      jsonPath: ".status.state"
    - name: Replicas
      type: string
      jsonPath: ".status.readyReplicas"
    - name: Primary-Endpoint
      type: string
      jsonPath: ".status.primaryEndpoint"
    - name: Age
      type: date
      jsonPath: ".metadata.creationTimestamp"
  - name: v4
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Status
      type: string
      jsonPath: ".status.state"
    - name: Replicas
      type: string
      jsonPath: ".status.roles.sql.readyReplicas"
    - name: Primary-Endpoint
      type: string
      jsonPath: ".status.endpoints.primary"
    - name: Age
      type: date
      jsonPath: ".metadata.creationTimestamp"
  - name: v5
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Status
      type: string
      jsonPath: ".status.state"
    - name: Replicas
      type: string
      jsonPath: ".status.roles.sql.readyReplicas"
    - name: Primary-Endpoint
      type: string
      jsonPath: ".status.endpoints.primary"
    - name: Age
      type: date
      jsonPath: ".metadata.creationTimestamp"
  - name: v6
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Status
      type: string
      jsonPath: ".status.state"
    - name: Replicas
      type: string
      jsonPath: ".status.roles.sql.readyReplicas"
    - name: Primary-Endpoint
      type: string
      jsonPath: ".status.endpoints.primary"
    - jsonPath: .spec.update.desiredVersion
      name: Desired-Version
      type: string
    - jsonPath: .status.runningVersion
      name: Running-Version
      type: string
    - name: Age
      type: date
      jsonPath: ".metadata.creationTimestamp"
  - name: v7
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Status
      type: string
      jsonPath: ".status.state"
    - name: Replicas
      type: string
      jsonPath: ".status.roles.sql.readyReplicas"
    - name: Primary-Endpoint
      type: string
      jsonPath: ".status.endpoints.primary"
    - jsonPath: .spec.update.desiredVersion
      name: Desired-Version
      type: string
    - jsonPath: .status.runningVersion
      name: Running-Version
      type: string
    - name: Age
      type: date
      jsonPath: ".metadata.creationTimestamp"
  conversion:
    strategy: None
  names:
    kind: SqlManagedInstance
    plural: sqlmanagedinstances
    shortNames:
    - sqlmi
  scope: Namespaced
