apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: telemetrycollectors.arcdata.microsoft.com
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  group: arcdata.microsoft.com
  versions:
  - name: v1beta1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Status
      type: string
      jsonPath: ".status.state"
    - name: Age
      type: date
      jsonPath: ".metadata.creationTimestamp"
  - name: v1beta2
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Status
      type: string
      jsonPath: ".status.state"
    - name: Age
      type: date
      jsonPath: ".metadata.creationTimestamp"
  - name: v1beta3
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
  - name: v1beta4
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
  - name: v1beta5
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              credentials:
                type: object
                properties:
                  certificates:
                    type: array
                    items:
                      type: object
                      properties:
                        certificateName:
                          type: string
                        secretName:
                          type: string
                        secretNamespace:
                          type: string
              collector:
                type: object
                properties:
                  receivers:
                    x-kubernetes-preserve-unknown-fields: true
                    type: object
                  processors:
                    x-kubernetes-preserve-unknown-fields: true
                    type: object
                  exporters:
                    x-kubernetes-preserve-unknown-fields: true
                    type: object
                  extensions:
                    x-kubernetes-preserve-unknown-fields: true
                    type: object
                  service:
                    type: object
                    properties:
                      pipelines:
                        type: object
                        additionalProperties:
                          type: object
                          properties:
                            receivers:
                              type: array
                              items:
                                type: string
                            processors:
                              type: array
                              items:
                                type: string
                            exporters:
                              type: array
                              items:
                                type: string
                      extensions:
                        type: array
                        items:
                          type: string
              resources:
                type: object
                properties:
                  limits:
                    type: object
                    additionalProperties:
                      type: object
                  requests:
                    type: object
                    additionalProperties:
                      type: object
              update:
                type: object
                properties:
                  desiredVersion:
                    type: string
          status:
            type: object
            properties:
              observedGeneration:
                type: integer
              runningVersion:
                type: string
              registryVersions:
                type: object
                properties:
                  next:
                    type: string
                  previous:
                    type: string
                  current:
                    type: string
                  latest:
                    type: string
                  behind:
                    type: integer
                  available:
                    type: array
                    items:
                      type: string
              releasedVersions:
                type: object
                properties:
                  next:
                    type: string
                  previous:
                    type: string
                  current:
                    type: string
                  latest:
                    type: string
                  behind:
                    type: integer
                  available:
                    type: array
                    items:
                      type: string
              arcDataServicesK8sExtensionLatestVersion:
                type: string
              endpoints:
                type: object
                additionalProperties:
                  type: string
              state:
                type: string
              healthState:
                type: string
              reason:
                type: string
              message:
                type: string
              lastUpdateTime:
                type: string
                format: date-time
          apiVersion:
            type: string
          kind:
            type: string
    subresources:
      status: {}
    additionalPrinterColumns:
    - jsonPath: .status.state
      name: Status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
  conversion:
    strategy: None
  names:
    kind: TelemetryCollector
    plural: telemetrycollectors
    shortNames:
    - telemetrycollector
  scope: Namespaced