apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: DataflowEndpoint
metadata:
  name: eventgrid
spec:
  endpointType: mqtt
  authentication:
    method: systemAssignedManagedIdentity
    systemAssignedManagedIdentitySettings:
      audience: https://eventgrid.azure.net
  mqttSettings:
    host: eventGridPlaceholder:8883
    tls:
      mode: Enabled
---
apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: Dataflow
metadata:
  name: my-topic-map
spec:
  profileRef: my-dataflow-profile
  operations:
  - operationType: source
    name: source1
    sourceSettings:
      endpointRef: mq
      dataSources:
        - "topic/#"
  - operationType: destination
    name: destination1
    destinationSettings:
      endpointRef: eventgrid
      dataDestination: factory-gateway-
---
apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: DataflowProfile
metadata:
  name: my-dataflow-profile
spec:
  instanceCount: 1