apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: DataflowEndpoint
metadata:
  name: mq-source
spec:
  endpointType: mqttSettings
  authentication:
    method: serviceAccountToken
    serviceAccountTokenSettings:
      audience: aio-mq
  mqttSettings:
    host: "aio-mq-dmqtt-frontend:1883"
    tls:
      mode: Enabled
---
apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: DataflowEndpoint
metadata:
  name: eventgrid
spec:
  endpointType: mqtt
  authentication:
    method: systemAssignedManagedIdentity
    systemAssignedManagedIdentitySettings:{audience: https://eventgrid.azure.net}
  mqttSettings:
    host: eventGridPlaceholder:8883
    tls:
      mode: Enabled
---
apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: Dataflow
metadata:
  name: my-dataflow
spec:
  profileRef: dataflowProfile
  mode: enabled
  operations:
  - operationType: source
    name: source1
    sourceSettings:
      endpointRef: mq-source
      dataSources:
        - "topic/#"
        - azure-iot-operations/data/#
  - operationType: destination
    name: destination1
    destinationSettings:
      endpointRef: eventgrid
      dataDestination: factory
---
apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: DataflowProfile
metadata:
  name: dataflowProfile
spec:
  instanceCount: 1
  diagnostics:
    logs:
      level: "debug"