apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium
volumeBindingMode: WaitForFirstConsumer
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Premium_LRS
  kind: managed