apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium
provisioner: disk.csi.azure.com
parameters:
  kind: Managed
  storageaccounttype: Premium_LRS
  cachingmode: ReadOnly 
volumeBindingMode: WaitForFirstConsumer