# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: managed-csi-premium
# provisioner: kubernetes.io/azure-disk
# parameters:
#   kind: Managed
#   storageaccounttype: Premium_LRS
#   cachingmode: ReadOnly 
# volumeBindingMode: WaitForFirstConsumer


kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azuredisk-csi
provisioner: disk.csi.azure.com
parameters:
  skuname: Premium_LRS 
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer