kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azuredisk-csi
provisioner: disk.csi.azure.com
parameters:
  skuname: Premium_LRS 
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer