apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: hello-arc
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  releaseName: nginx-ingress
  chart:
    spec:
      chart: ./artifacts/hello-arc/charts/nginx-ingress
  values:
    controller:
      image:
        repository: k8s.gcr.io/ingress-nginx/controller
        tag: "v1.1.1"
      replicaCount: 3