{
 "title": "Store / Shopper Insights",
 "tags": [ "stores" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Store", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Aisle Zone", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<div style=\"font-size: 30px; color: black; background-color: green; text-align: center;\">\n  Aisle Zone\n</div>\n"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "current_shoppers{camera=~\".*stream.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "total_shoppers{camera=~\".*stream.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "shoppers_age_10", "legendFormat": "__auto" },
    { "expr": "shoppers_age_20", "legendFormat": "__auto" },
    { "expr": "shoppers_age_30", "legendFormat": "__auto" },
    { "expr": "shoppers_age_40", "legendFormat": "__auto" },
    { "expr": "shoppers_age_50", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Shoppers (by Age)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 3 },
   "targets": [
    { "expr": "shoppers_age_10", "legendFormat": "__auto" },
    { "expr": "shoppers_age_20", "legendFormat": "__auto" },
    { "expr": "shoppers_age_30", "legendFormat": "__auto" },
    { "expr": "shoppers_age_40", "legendFormat": "__auto" },
    { "expr": "shoppers_age_50", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "detected_total_persons", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Detected Total Persons",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 5, "y": 13 },
   "targets": [
    { "expr": "detected_total_persons", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "detection_fps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Detection frame per seconds",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 13 },
   "targets": [
    { "expr": "detection_fps", "legendFormat": "__auto" }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } }
 ]
}