{
 "title": "Store / Point-of-Sale (PoS) Assets Health",
 "tags": [ "stores" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Store", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Point-of-Sale(PoS)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PoS Errors (Top 5)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5,sum(pos_failure_count_total) by (device_id,failure_type))",
     "legendFormat": "{{device_id}} - {{failure_type}}"
    }
   ]
  },
  {
   "title": "PoS Errors (by failure type)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5,sum(pos_failure_count_total) by (failure_type))",
     "legendFormat": "{{device_id}}"
    }
   ]
  },
  {
   "title": "POS items Sold (last 1 hour)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(pos_items_sold_total[1h])",
     "legendFormat": "{{device_id}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  { "title": "Self-Checkout", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Self-Checkout Errors (last 1 hour)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(auto_checkout_errors_total[1h])",
     "legendFormat": "{{device_id}}"
    }
   ]
  },
  {
   "title": "Self-Checkout Items Scanned (last 1 hour)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(auto_checkout_items_scanned_total[1h])",
     "legendFormat": "{{device_id}}"
    }
   ]
  },
  {
   "title": "Self-Checkout Items Scanned (last 1 day)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(auto_checkout_items_scanned_total[1d])",
     "legendFormat": "{{device_id}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  { "title": "Smart Shelf", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Smart Shelf Stock Level",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "topk(10,sum(smart_shelf_stock_level) by (device_id, product_id))",
     "legendFormat": "{{device_id}} - {{product_id}}"
    }
   ]
  },
  {
   "title": "Smart Shelf Threshold",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "topk(10,sum(smart_shelf_threshold) by (device_id, product_id))",
     "legendFormat": "{{device_id}} - {{product_id}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  { "title": "Scale", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Scale Tare Weight",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    { "expr": "scale_tare_weight_kg", "legendFormat": "{{device_id}}" }
   ]
  },
  {
   "title": "Scale Weight",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    { "expr": "scale_weight_kg", "legendFormat": "{{device_id}}" }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } }
 ]
}