
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: arcdata-installer-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - arcdata.microsoft.com
  resources:
  - datacontrollers
  verbs:
  - create
  - get
  - list

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arcdata-installer-role-binding
subjects:
- kind: User
  name: {{INSTALLER_USERNAME}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: arcdata-installer-role