name: Connet Azure Arc and EKS

on: workflow_dispatch

jobs:
  connect-eks-and-arc:
    name: Connect
    runs-on: ubuntu-latest
    environment: PoC

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - run: |
        python --version
        python -m pip install awscli
        aws --version
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        export AWS_DEFAULT_REGION=us-west-2
        aws eks --region us-west-2 update-kubeconfig --name ${{ secrets.EKSCLUSTER_NAME }}
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az login --service-principal -u ${{ secrets.CLIENTID }} -p ${{ secrets.CLIENTSECRET }} --tenant ${{ secrets.TENANTID }}
        az acr helm install-cli --client-version 3.6.1 --yes
        az config set extension.use_dynamic_install=yes_without_prompt
        az connectedk8s connect --name ${{ secrets.EKSCLUSTER_NAME }} --resource-group ${{ secrets.AZURE_RG }} --location ${{ secrets.AZURE_REGION }}
