---
    # Variables here are applicable to all host groups
    
    resource_group: "Arc-AWS-Demo"
    tenant_id: "<Azure Tenant ID>"
    azure_region: "westus2"
    subscription_id: "<Azure Subscription ID>"