name: Scan templates

on:
  push:
    branches: [ release_checker ]
  pull_request:
    branches: [ release_checker ]

jobs:
  scan-templates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Scan templates
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm start ${{ github.workspace }}
        env:
          EXCLUDED_FOLDERS: 'docs,tests'
      - name: Save report
        run: echo ${{ steps.scan-templates.outputs.report }} > scan-report.json
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: scan-report
          path: scan-report.json
