name: Check API versions in Azure templates

on:
  push:
    branches:
      - release_checker

jobs:
  check-api-versions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Setup PowerShell
      uses: microsoft/setup-powershell@v1
    - name: Install required modules
      run: Install-Module -Name Az -Force -AllowClobber
    - name: Run script
      run: |
        $results = tests\check-api-versions.ps1 -Repository ${{ github.repository }} -Branch ${{ github.ref }}
        $results.Table
