name: Check API versions

on:
  push:
    branches:
      - main

jobs:
  check-api-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Azure CLI
        uses: azure/setup-azure-cli@v1
        with:
          install-cli: true
      - name: Run script
        run: |
          chmod +x tests/GetAzAPI.sh
          ./tests/GetAzAPI.sh
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: report.json
