name: Check API versions in Azure templates

on:
  push:
    branches:
      - release_checker

jobs:
  check-api-versions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Install PowerShell
      run: |
        sudo apt-get update
        sudo apt-get install -y powershell
    - name: Install required modules
      run: pwsh -Command "Install-Module -Name Az -Force -AllowClobber"
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2   
    - name: Run script
      id: check-api-versions
      run: |
        $output = tests/check-api-versions.ps1 -Repository ${{ github.repository }} -Branch ${{ github.ref }}
        if ($output.Table) {
          echo $output.Table
        }
      shell: pwsh

