name: Scan Azure resource API versions

on:
  push:
    branches:
      - release_checker

jobs:
  scan-resources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Scan resources
        run: node tests/scan-resources.js ./ docs,tests > report.json

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: report.json
