name: Azure API Version Checker

on:
  push:
    branches:
      - main

jobs:
  check-templates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Azure CLI
        uses: azure/setup-azure-cli@v1
      
      - name: Check templates
        run: |
          # Scan ARM templates and Bicep templates
          find . -type f -not -path './.github/*' -not -name '*.yaml' -not -name '*.yml' -name '*.json' -or -name '*.bicep' | while read file
          do
            az deployment sub list-api-versions --template-file $file --output json >> output.json
          done
          
          # Scan Terraform templates
          find . -type f -not -path './.github/*' -not -name '*.yaml' -not -name '*.yml' -name '*.tf' | while read file
          do
            az provider show -n $(grep provider $file | awk '{print $2}' | tr -d '"') --query "resourceTypes[].{resourceType:resourceType, apiVersion:apiVersions[0]}" --output json >> output.json
          done
          
          # Print report
          cat output.json | jq '.[] | {resourceType:.resourceType, currentApiVersion:.apiVersion, latestApiVersion:.resourceType+"/"+.apiVersion}' | sort -u | jq -s . > report.json
          
      - name: Save report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: report.json
