name: Check Azure API versions

on:
  push:
    branches:
      - release_checker

jobs:
  check-api-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Azure CLI
        run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: Run script
        run: |
          chmod +x tests/GetAzAPI.sh
          ./tests/GetAzAPI.sh
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: report.json
      - name: Display report
        run: cat report.json