name: Check API versions in Azure templates

on:
  push:
    branches:
      - release_checker

jobs:
  check-azure-apis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup PowerShell
      uses: microsoft/setup-powershell@v1
      
    - name: Run script
      run: pwsh -File tests/check-api-versions.ps1
        
    - name: Upload report
      uses: actions/upload-artifact@v2
      with:
        name: report
        path: report.json

    - name: Show report
      uses: actions/http-client@v1
      with:
        url: ${{ steps.upload_report.outputs.artifacts.report }} # Download the report from the artifact
        method: GET # Use the GET method to download the report
        headers: | # Set the headers for the request
          Accept: application/json
      id: show_report # Assign an ID to the step
      
    - name: Display report
      run: |
        Write-Host "Report:"
        Write-Host ${{ steps.show_report.outputs.body }} # Display the response body in the console
