name: Azure API version check

on:
  push:
    branches:
      - release_checker

jobs:
  check-api-versions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      
    - name: Find JSON, Terraform, and Bicep files
      run: |
        find . -type f \( -name "*.json" -o -name "*.tf" -o -name "*.bicep" \) \
        -not -path "./tests/*" \
        -not -path "./docs/*" \
        -print > file_list.txt
      
    - name: Check API versions
      run: |
        while read filename; do
          # Extract resource types and API versions
          # Check if API version is outdated
          # Generate report
          # Append report to output file
        done < file_list.txt
      
    - name: Generate report
      run: |
        cat output.txt | jq -s 'group_by(.ResourceType) | map({"ResourceType": .[0].ResourceType, "Count": length, "Files": [.[] | {"File": .Filename, "APIVersion": .APIVersion}]})' > report.json
        
    - name: Upload report
      uses: actions/upload-artifact@v2
      with:
        name: API report
        path: report.json
