name: Query latest release

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  check-releases:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run script
      run: python tests/QueryReleases.py

    - name: Display report
      run: cat tests/QueryReleases.txt
