name: 'Stale issue handler'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@main
        id: stale
        with:
          stale-issue-message: 'This issue has been automatically marked as stale because it has been open 21 days with no activity. It will be closed in 5 days if no further activity occurs.'
          days-before-stale: 21
          days-before-close: 5
          exempt-issue-labels: 'blocked,must,should,keep,pinned'
      - name: Print outputs
        run: echo ${{ join(steps.stale.outputs.*, ',') }}